### ISSUE TITLE
Add immunity?

### ISSUE THREAD

**Issue by NotJustin** [NotJustin/SkillAutoBalance#10]
Should I make it so people with certain flags can be immune to balance?

I do not think it makes sense, but I will leave this here to see if someone can convince me otherwise.

**Comment by WhyFaust** [comment]
No, the point of doing such nonsense?
But immunity from force join - you can :3.

**Comment by NotJustin** [comment]
Okay, immunity from force join. When they join the server, they will be put in spectate. They can join a team when they are ready. If you have BlockTeamSwitch cvar they will still only join the smallest team when they do want to leave spectate.

Is it better to add this as immunity, or as a client preference for everyone?
They can choose:

"When I join the server:"
1. Put me on a team
2. Put me on spectator"

**Comment by WhyFaust** [comment]
Yeah, you can do that.

**Comment by NotJustin** [comment]
Okay, I am also going to change ForceJoinTeam to be like this.

0 = Disabled
1 = Optional (players can choose if they want to be forced on a team when they join in !settings)
2 = Forced (players cannot choose what they want)
