### ISSUE TITLE
Add SM:RPG support

### ISSUE THREAD

**Issue by Z-RAY-Z** [NotJustin/SkillAutoBalance#14]
Can you add support for this mod https://github.com/peace-maker/smrpg ?
It's ankther RPG mod like NC RPG.

**Comment by NotJustin** [comment]
Can you help by answering these questions?

What is a player's "level"?
What is a player's "rank"?

My plugin assumes best players have highest points/rank/level and worst players have lowest. I need to know whether I should use `SMRPG_GetClientRank`, `SMRPG_GetClientLevel`, or `SMRPG_GetClientExperience`.

**Comment by Z-RAY-Z** [comment]
Player's rank - player position in lvl's ladder. Sorted by level.
Player's level - general player level, like other RPG-systems.
Player's expirience - exp you need earn for get lvl-up. I think, it's useless for balance-purpose.

**Comment by NotJustin** [comment]
So rank 1 = player with highest level? I should use level then.

**Comment by Z-RAY-Z** [comment]
> So rank 1 = player with highest level?

Yes, it is.

**Comment by NotJustin** [comment]
Added, let me know if you have any problems.

**Comment by NotJustin** [comment]
I am an idiot and only just pushed the latest files now, in case you tried since I commented 40 minutes ago.

**Comment by WhyFaust** [comment]
Why create a separate score type? You can just create one (6 - RPG) and execute code depending on the loaded kernel. For example:
```
else if (scoreType == TYPE_RPG)
{
   if (g_UsingSMRPG)
   {
      g_iClientScore[client] = float(SMRPG_GetClientLevel(client));
      CreateTimer(0.1, Timer_CheckScore, GetClientUserId(client), TIMER_FLAG_NO_MAPCHANGE);
   }
   else if(g_UsingNCRPG)
   {
      g_iClientScore[client] = NCRPG_GetSkillSum(client);
      CreateTimer(0.1, Timer_CheckScore, GetClientUserId(client), TIMER_FLAG_NO_MAPCHANGE);
   }
   else
   {
      LogError("RPG not found. Use other score type");
   }
}
```

**Comment by NotJustin** [comment]
What if a server operator has more than one of (RankMe, gameME, SMRPG, NCRPG, etc.) running? I know, this sounds like nonsense, but I cannot trust that other people have brains 😄 

I think it is safer this way.

**Comment by WhyFaust** [comment]
No, two or more RPG plug-ins 1000% can't stand on the same server at the same time, firstly it won't work like that - they will conflict with each other, secondly it's useless.

**Comment by NotJustin** [comment]
You are not wrong. I have another plan.

My next goal is to see if I can pair the boolean `scoreType` with each plugin's native so that I can use a lot less lines in this area.
