### ISSUE TITLE
Errors with InitializeClient GlobalForward

### ISSUE THREAD

**Issue by NotJustin** [NotJustin/SkillAutoBalance#43]
I'm not quite sure what is this but I get such error in logs - 

03/14/2021 - 12:25:37: Info (map "aim_deagle7k") (file "/home/container/csgo/addons/sourcemod/logs/errors_20210314.log")
L 03/14/2021 - 12:25:37: [SM] Exception reported: Cannot push parameters when there is no call in progress
L 03/14/2021 - 12:25:37: [SM] Blaming: pub/sab-blockteams.smx
L 03/14/2021 - 12:25:37: [SM] Call stack trace:
L 03/14/2021 - 12:25:37: [SM]   [0] Call_PushCell
L 03/14/2021 - 12:25:37: [SM]   [1] Line 420, C:\Users\Justin\Desktop\Downloads_Uncluttered\_spcode\spcode\sourcepawn\configs\sm_1_10_0_6478\sab-blockteams.sp::Frame_AlternateJoinTeam
L 03/14/2021 - 12:25:38: [SM] Exception reported: Maximum number of parameters reached
L 03/14/2021 - 12:25:38: [SM] Blaming: pub/sab-blockteams.smx
L 03/14/2021 - 12:25:38: [SM] Call stack trace:
L 03/14/2021 - 12:25:38: [SM]   [0] Call_PushCell
L 03/14/2021 - 12:25:38: [SM]   [1] Line 420, C:\Users\Justin\Desktop\Downloads_Uncluttered\_spcode\spcode\sourcepawn\configs\sm_1_10_0_6478\sab-blockteams.sp::Frame_AlternateJoinTeam

_Originally posted by @oligarhs420 in https://github.com/NotJustin/SkillAutoBalance/issues/42#issuecomment-798942082_

Referring to this line: https://github.com/NotJustin/SkillAutoBalance/blob/master/scripting/sab-blockteams.sp#L420

**Comment by NotJustin** [comment]
I do not understand why either of these errors are occurring to be honest. Are there any other errors before this?

**Comment by NotJustin** [comment]
>asherkin — Today at 2:32 PM
>you should absolutely not be calling a function in the middle of pushing the params, get everything ready then push them all - I suspect your error is another plugin doing a dynamic call in a callback being triggered by ChangeClientTeam - call params are a global state

This should be why it happens.

**Comment by rcon420** [comment]
> I do not understand why either of these errors are occurring to be honest. Are there any other errors before this?

sadly I deleted older logs no new logs now. Also, I think you should make for this plugin discord server, to be honest, so we can help each other easier and People can easier troubleshoot problems in one place.
