### ISSUE TITLE
Late load support

### ISSUE THREAD

**Issue by xhaooy** [NotJustin/SkillAutoBalance#44]
hi, could you add late load support?
atm i have those issues:
on map where this plugin(s) is loaded [sab/sab-core.smx] Attempting to use score from plugin kento_rankme, but it is not loaded
and when i unload this plugin(s) players cannot use teammenu and they are assigned automatically, no error logs

**Comment by NotJustin** [comment]
Thank you for posting this. You have revealed a problem for me.

I check when the scoretype convar is changed when the plugin is loaded. If the scoretype is not auto, I immediately check if the scoretype you want to use is loaded. If it didn't load yet, then it will show the error you see.

I need to make sure to only check the scoretype after OnConfigsExecuted (which only occurs after all plugins are loaded).

Will push a hotfix in a couple of minutes.

**Comment by xhaooy** [comment]
thanks :)

**Comment by NotJustin** [comment]
Please reopen if you notice the issue still occurs.

**Comment by xhaooy** [comment]
sorry for delay. now i have this again:
[sab/sab-core.smx] Attempting to use score from plugin kento_rankme, but it is not loaded

its on late load. when plugin(s) is unloaded everything is fine

**Comment by NotJustin** [comment]
This whole time, I've been using the library 'kento_rankme' when I should've been using the library 'rankme'.

So, kento rankme scoretype NEVER WORKED until today.

Embarassing for me. 👎
