### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by WhyFaust** [NotJustin/SkillAutoBalance#6]
```
[SM] Exception reported: Couldn't find gamerules proxy entity
[SM] Blaming: skillautobalance.smx
[SM] Call stack trace:
[SM]   [0] GameRules_SetProp
[SM]   [1] Line 184, skillautobalance.sp::UpdateTeamMenu
[SM]   [2] Line 170, skillautobalance.sp::OnConfigsExecuted
```

**Comment by NotJustin** [comment]
I got advice on the AlliedModders Discord that this can occur if I try to use GameRules_SetProp before the map is loaded. Adding a check to only use the function after the map is loaded, let me know if you still have the issue.
